### ISSUE TITLE
Support locating desired tasks based on tag

### ISSUE THREAD

**Issue by wenlzhang** [uphy/obsidian-reminder#10] opened 2021-08-27 10:27 UTC
Supporting locating desired tasks based on tag, in addition to the format `(@2021-08-14 09:37)`, would help better manage tasks from the tag pane and have a consistent tag definition for other tasks that do not have such tags. For instance, this plugin may look for tasks defined in the format of `- [ ] Task #Task 📅 2021-08-27T09:37`.

Moreover, supporting this would help better integrating with Obsidian Tasks, which uses a global filter/tag for locating tasks managed by it.
[schemar/obsidian-tasks: Task management for the Obsidian knowledge base.](https://github.com/schemar/obsidian-tasks)

**Comment by uphy** [comment] 2021-08-29 12:59
I'm planning to support Obsidian Tasks Plugin style TODOs.
Please wait for it.

**Comment by wenlzhang** [comment] 2021-08-29 14:09
That's great news! Really looking forward to the that!

The following discussion may be relevant to the discussion:
https://github.com/schemar/obsidian-tasks/discussions/64#discussioncomment-1247795

**Comment by schemar** [comment] 2021-08-29 16:21
Thank you for bringing this up @wenlzhang and than you @uphy for planning on supporting Tasks. I would love to use this together with tasks. And I really like that reminders is a separate plugin and won’t bloat Tasks. Thank you for this plugin! ❤️

**Comment by imeed166** [comment] 2021-08-30 16:18
This [comment](https://github.com/schemar/obsidian-tasks/discussions/64#discussioncomment-1254968) summarize the problems I'm currently having when working with the 2 plugins together.

**Comment by uphy** [comment] 2021-08-31 11:26
@wenlzhang I introduced experimental support for tasks plugin.  Can you try v1.0.5?
(`#tag` is not supported yet)

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1233373/131494472-68f3a20e-de40-4ece-ac4c-d68149095e46.png">

**Comment by wenlzhang** [comment] 2021-08-31 12:10
@uphy Thanks for supporting this! According to the discussion as follows, I realize that the reminder date/time may not be necessary the same as the due date/time.

https://github.com/schemar/obsidian-tasks/discussions/64#discussioncomment-1247118

Therefore, it would be great to be able to use different (emoji) symbol for signifying the reminder date/time, to avoid confusion, if possible. For instance, the reminder may look something like the following:

`- [ ] Task #Reminder 🗓️ 2021-08-28 12:00 #Task #Life 📅 2021-08-30`

Should a space (this looks better for me) be inserted between the symobl and the data/time? Or it does not matter?

**Comment by uphy** [comment] 2021-09-03 12:26
@wenlzhang Sorry but I misunderstood your feature request.

Would your request be to introduce a feature that only considers TODO list items that contain tags (`#Tag`) as reminder task? (like Obsidian Tasks Plugin's global filter)

> Therefore, it would be great to be able to use different (emoji) symbol for signifying the reminder date/time, to avoid confusion

I feel TODO item sentence becomes too long to read.
I don't want to add new time field.
Why do you want to introduce another emoji symbol? 
Current implementation seems not confusing for me.

> Should a space (this looks better for me) be inserted between the symobl and the data/time? Or it does not matter?

It will be fixed in the next version.
Space is inserted based on the TODO item's another symbols.
Also, incorrect symbol order will be fixed.  (do not break your task format)

**Comment by wenlzhang** [comment] 2021-09-03 13:00
> Would your request be to introduce a feature that only considers TODO list items that contain tags (`#Tag`) as reminder task? (like Obsidian Tasks Plugin's global filter)

Yes. This request can be explained as follows:

- I would add `#Task` (Obsidian Tasks Plugin's global filter) to important tasks in my project.
- I would add `#Reminder` (this can be Obsidian Reminder's global filter, for example) to tasks that need reminders.

Maybe this `#Reminder` tag can be hidden in preview mode, like what one can do with the Tasks plugin.

> I feel TODO item sentence becomes too long to read.
> I don't want to add new time field.

This indeed can be problematic. This point is also discussed in the following issue.

[Have a "short" mode which shows emoji details only on hover · Discussion #108 · schemar/obsidian-tasks](https://github.com/schemar/obsidian-tasks/discussions/108)

In case of the Reminder plugin, maybe certain task details, e.g. all tags, can be hidden when showing the reminder in the pop-up window. For instance, `- [ ] Task #Reminder 🗓️ 2021-08-28 12:00 #Task #Life 📅 2021-08-30` may become `- [ ] Task 🗓️ 2021-08-28 12:00 📅 2021-08-30` when showing the reminder. Or maybe all time info can be hidden when showing the reminder? One may customize these in the plugin configuration pane.

> Why do you want to introduce another emoji symbol?

I was thinking that

- One emoji may represent that it is a reminder (managed by the Reminder plugin) that has a reminder date/time.
- Another different emoji represents that it is a task that has a due date/time (managed by the Tasks plugin).

The reason for this is that the reminder date/time may be different from the due date/time. For instance, one may want to be reminded a few days before the due date.

Considering this point and the use of a customized tag for denoting reminders managed by the Reminder plugin, one may allow for checking the corresponding tasks from the search pane. Even better, maybe one can query tasks that has reminders, like what one can do with the Tasks plugin? Of course, this may be a separate feature request.

> Current implementation seems not confusing for me.

This is true, as the current implementation treats the due date/time as the reminder date/time, if the Tasks format is used for denoting reminders.

**Comment by imeed166** [comment] 2021-09-03 13:52
I think adding a [tag before the task](https://github.com/uphy/obsidian-reminder/issues/10#issuecomment-912520274) or [supporting the task plugin format](https://github.com/uphy/obsidian-reminder/issues/10#issuecomment-909147993) would overcomplicate this process.
Isn't it simpler to keep each plugin format separated, and just add a reminder with the current syntax at the end if the user wants a task + a reminder ?

**Comment by wenlzhang** [comment] 2021-09-03 13:59
> Isn't it simpler to keep each plugin format separated, and just add a reminder with the current syntax at the end if the user wants a task + a reminder ?

Indeed. It might complicate the Reminder plugin. 😅

Would it be possible to query/list all tasks that have reminders then? Maybe syntax like the following would list all tasks that have reminders in preview mode.
'''reminder
not done
'''

**Comment by uphy** [comment] 2021-09-04 10:46
@wenlzhang Thank you for your response.

I think the default reminder format(`(@YYYY-MM-DD)`) is suitable for having separate due date and remind date.  (Because it is unique and doesn't conflict with other plugins)
However, for visual compatibility with the tasks plugin, I feel it might be a good idea to introduce a new emoji, as you mentioned.

**Comment by wenlzhang** [comment] 2021-09-04 13:47
> I think the default reminder format(`(@YYYY-MM-DD)`) is suitable for having separate due date and remind date.

@uphy Yes, I agree. If one only enable the default reminder format, i.e. `(@YYYY-MM-DD)`, one can get a reminder at the set reminder date/time; if one enable both the default reminder format and the Tasks plugin format, one can get an additional reminder at due date/time. This might be of interest in some cases.

**Comment by uphy** [comment] 2021-09-14 11:57
@wenlzhang I added custom emoji `⏰` as reminder symbol for tasks plugin format.
Maybe it's interesting feature for you, too.

https://github.com/uphy/obsidian-reminder/issues/17#issuecomment-919073489

**Comment by uphy** [comment] 2021-09-14 22:11
@wenlzhang It's not reproduced.  My expectation of the behavior is that both will be recognized as reminder.

Is your Date and Time format `YYYY-MM-DDTHH:mm` correctly?

**Comment by wenlzhang** [comment] 2021-09-14 22:36
> Is your Date and Time format `YYYY-MM-DDTHH:mm` correctly?

I think it would be set correctly, as can be seen from Figure 2.

As can be seen from the right side pane of Figure 1, only the first is recognized as a reminder, but not the second one.

Figure 1:
<img width="1247" alt="Screenshot 2021-09-15 at 00 31 48" src="https://user-images.githubusercontent.com/44930227/133342649-c7569796-8ccc-4341-a066-8487f17e6e37.png">

Figure 2:
<img width="1152" alt="Screenshot 2021-09-15 at 00 33 25" src="https://user-images.githubusercontent.com/44930227/133342657-3cae26bc-99a2-4356-a16c-d45ea9d0b47d.png">

**Comment by uphy** [comment] 2021-09-14 22:43
Does it have newline?
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/1233373/133343307-efff9119-5322-4dba-b307-a1732a3f14c6.png">
Reminder plugin's task should be one line.

If there are no newlines, it seems strange...

**Comment by wenlzhang** [comment] 2021-09-14 22:50
Indeed. The following task would give a reminder: `- [ ] Test Tasks and Reminder Tasks format #ToDoReminder #ToDoTask #CategoryTool ⏰ 2021-09-15T12:00 📅 2021-09-14`.

Just to confirm, to make Reminder recognize the time info correctly, there should be nothing but date/time between these two emojis: `⏰ 2021-09-15T12:00 📅 `. Is this correct?

**Comment by uphy** [comment] 2021-09-15 00:41
Yes, it is correct.  This is also should be documented.

**Comment by uphy** [comment] 2021-11-03 04:25
document: 
https://uphy.github.io/obsidian-reminder/guide/interop-tasks.html#distinguish-due-date-and-reminder-date

**Closed by uphy** 2021-11-03 04:25 UTC
Labels: enhancement
